services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: api_app
    depends_on:
      - db
    command: ["app/docker/app.sh"]
    ports:
      - "1234:8000"
    volumes:
      - ./app:/src

  nginx:
    container_name: "nginx"
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/nginx/conf.d
      - ./nginx/nginx.conf:/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
      - pgadmin
      - db
    links:
      - app