"""25.05

Revision ID: b073de0b15e8
Revises: ed20885ebc58
Create Date: 2024-05-25 19:43:47.851175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b073de0b15e8'
down_revision: Union[str, None] = 'ed20885ebc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name')
    # ### end Alembic commands ###
