"""25.05

Revision ID: bf4c3b0646bf
Revises: 87a4c37bda1d
Create Date: 2024-05-25 19:17:21.186873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4c3b0646bf'
down_revision: Union[str, None] = '87a4c37bda1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_to_question', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer_to_question', 'test', ['test_id'], ['id'])
    op.drop_constraint('test_question_id_fkey', 'test', type_='foreignkey')
    op.drop_column('test', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('test_question_id_fkey', 'test', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'answer_to_question', type_='foreignkey')
    op.drop_column('answer_to_question', 'test_id')
    # ### end Alembic commands ###
