"""25.05

Revision ID: efe169fb5348
Revises: 8e6ff00d2639
Create Date: 2024-05-25 19:02:51.050850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe169fb5348'
down_revision: Union[str, None] = '8e6ff00d2639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task')
    op.drop_constraint('answer_question_id_fkey', 'answer', type_='foreignkey')
    op.drop_column('answer', 'question_id')
    op.add_column('answer_to_question', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.drop_column('answer_to_question', 'right_answer_id')
    op.add_column('lection', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('lection', sa.Column('description', sa.String(), nullable=True))
    op.add_column('lection', sa.Column('name', sa.String(), nullable=True))
    op.add_column('question', sa.Column('question', sa.String(), nullable=True))
    op.drop_constraint('question_course_id_fkey', 'question', type_='foreignkey')
    op.drop_column('question', 'title')
    op.drop_column('question', 'course_id')
    op.add_column('test', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'question', ['question_id'], ['id'])
    op.add_column('user', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'image_path')
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'question_id')
    op.add_column('question', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('question_course_id_fkey', 'question', 'course', ['course_id'], ['id'])
    op.drop_column('question', 'question')
    op.drop_column('lection', 'name')
    op.drop_column('lection', 'description')
    op.drop_column('lection', 'file_path')
    op.add_column('answer_to_question', sa.Column('right_answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('answer_to_question', 'is_correct')
    op.add_column('answer', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('answer_question_id_fkey', 'answer', 'question', ['question_id'], ['id'])
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_in_course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_in_course_id'], ['student_in_course.id'], name='task_student_in_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.drop_table('result')
    # ### end Alembic commands ###
